#!/bin/sh
#SBATCH --time=48:00:00
#SBATCH --signal=USR2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=70
#SBATCH -p compute
#SBATCH -q batch
#SBATCH --mem=700G
#SBATCH --output=job.%j
module load R
export R_LIBS_USER=$HOME/.local/share/renv/library
cd /path/to/this/folder
Rscript -e 'if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")'
Rscript -e 'renv::restore()'
Rscript refpeakpicking.R
Rscript peakpicking.R
